CREATE TABLE Quiz (
  id        VARCHAR(36)   PRIMARY KEY,
  name      VARCHAR(255)  NOT NULL,
  userId    VARCHAR(36)   REFERENCES Users(id),
  createdAt TIMESTAMP     WITHOUT TIME ZONE DEFAULT now(),
  updatedAt TIMESTAMP     WITHOUT TIME ZONE DEFAULT now(),
  deletedAt TIMESTAMP     WITHOUT TIME ZONE
);

CREATE TABLE QuizQuestion (
  id        VARCHAR(36)   PRIMARY KEY,
  quizId    VARCHAR(36)   REFERENCES Quiz(id),
  name      VARCHAR(255)  NOT NULL,
  createdAt TIMESTAMP     WITHOUT TIME ZONE DEFAULT now(),
  updatedAt TIMESTAMP     WITHOUT TIME ZONE DEFAULT now(),
  deletedAt TIMESTAMP     WITHOUT TIME ZONE
);

CREATE TABLE QuizChoice (
  id          VARCHAR(36) PRIMARY KEY,
  questionId  VARCHAR(36) REFERENCES QuizQuestion(id),
  name        VARCHAR(255) NOT NULL,
  isCorrect   BOOLEAN,
  createdAt   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updatedAt   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  deletedAt   TIMESTAMP WITHOUT TIME ZONE
);