CREATE TABLE Quiz (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  user_id VARCHAR(36) REFERENCES Users(id),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  deleted_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE QuizQuestion (
  id VARCHAR(36) PRIMARY KEY,
  quiz_id VARCHAR(36) REFERENCES Quiz(id),
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  deleted_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE QuizChoice (
  id VARCHAR(36) PRIMARY KEY,
  question_id VARCHAR(36) REFERENCES QuizQuestion(id),
  name VARCHAR(255) NOT NULL,
  correct BOOLEAN,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  deleted_at TIMESTAMP WITHOUT TIME ZONE
);